# Generated by Django 4.2.19 on 2025-02-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_activeuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveUser',
        ),
    ]
